M1 review
UBC-MDS/exploratory-data-viz pull request #26
Opened 2021-01-13 02:51 UTC by hfboyce

Alterations for consistency and question amendments.

2021-01-19 19:06 UTC, ttimbers commented
On module 1, chapter 2, the first question's formatting appears off (at least using Netlify's preview rendering):

<img width="813" alt="Screen Shot 2021-01-19 at 11 05 05 AM" src="https://user-images.githubusercontent.com/6865016/105080942-64c86f80-5a46-11eb-9ced-db4b0e22a22e.png">

2021-01-19 19:11 UTC, hfboyce commented
@ttimbers I fixed the above. It's just rendering.

2021-01-19 19:19 UTC, ttimbers commented
This is also weird - the text code output (black box):

<img width="1319" alt="Screen Shot 2021-01-19 at 11 18 28 AM" src="https://user-images.githubusercontent.com/6865016/105082281-29c73b80-5a48-11eb-9c6d-06e2db2f66dd.png">

2021-01-19 19:41 UTC, ttimbers commented
Can we get them to make a simple plot in module 1, chapter 4? That would be very rewarding and motivating I think. Or is this a technical limitation?

2021-01-19 20:06 UTC, ttimbers commented
Not sure if I agree with this question in module 1, chapter 7:

#### Question 1
When combining plots in Altair, we say that each plot has its own ___.
- Overlay
- Layer
- Panel

To me a plot == Chart, and in altair, a chart is a layer. And we layer compatible charts on top of each each other to build more complex plots.  So a plot having a layer sounds a bit odd to me... So I think we need to modify or replace this question?

2021-01-19 20:15 UTC, ttimbers commented
Can we bold "Before going further take a look at the stock data." in module 1, exercise 9 to make it extra clear this needs to be done. Maybe even add, click Run code to do this before uncommenting the plot code and creating the visualization.

2021-01-19 20:18 UTC, ttimbers commented
Also, for module 1, question 9, when I click submit and run the code to see if I got it right, the plot disappears and then I cannot easily answer the next question:

<img width="804" alt="Screen Shot 2021-01-19 at 12 17 31 PM" src="https://user-images.githubusercontent.com/6865016/105088177-6434d680-5a50-11eb-99f3-dfae103b76cc.png">

2021-01-19 20:21 UTC, ttimbers commented
This also happens in module 1, question 10.

2021-01-19 20:23 UTC, ttimbers commented
As a learner, I do not like the "Use the code from exercise 9 above as a base." (I saw this in module 1, question 10). because when you go back, your answer you typed out is gone, and so you have to redo it, then remember to copy it. Let's avoid these and just give them the scaffolding needed.

2021-01-19 20:31 UTC, ttimbers requested changes
Some more smallish things to address.

2021-02-04 19:06 UTC, joelostblom commented on chapters/en/slides/module1/module1_01.Rmd
> +70s.</a>
Ok let's add parentheses around it

2021-02-04 19:07 UTC, joelostblom commented on chapters/en/slides/module1/module1_03.Rmd
> +To enrich this display of information further,
Yes!

2021-02-04 19:07 UTC, joelostblom commented on chapters/en/slides/module1/module1_03.Rmd
> +than the lighter ones,
Yup let's comment on that too

2021-02-04 19:42 UTC, joelostblom commented
> To me a plot == Chart, and in altair, a chart is a layer. And we layer compatible charts on top of each each other to build more complex plots. So a plot having a layer sounds a bit odd to me... So I think we need to modify or replace this question?

I think this does not matter much, so happy either way. According to the docs, we are technically layering *views of charts*. This makes it unclear if a chart *is*, *has*, or *exists in* a layer. In ggplot I believe a plot and a layer are the same. @hfboyce Let's change the wording to :

> Which function do we need to use to superimpose plots in Altair?
>
>- `overlay`
>- `layer`
>- `panel`

2021-02-09 00:01 UTC, hfboyce commented
> Also, for module 1, question 9, when I click submit and run the code to see if I got it right, the plot disappears and then I cannot easily answer the next question. 

Can't find an easy solution to this since right now all the fixes I've try only returns the text `alt.Chart(...)` I'll talk to @joelostblom  about this before our meeting where we would talk about a solution. 

All other comments have been addressed and pushed. 

@joelostblom should I merge now?

2021-02-09 00:55 UTC, joelostblom commented
@hfboyce Yes, just resolve all the comments that you have addressed and leave the one that are for me open

2021-02-09 17:42 UTC, hfboyce commented
@joel I resolved everything in this PR including the comments on the slide so you may want to hop on this branch and take a look. I think this is ready to merge.

2021-02-24 18:19 UTC, hfboyce commented
Can I merge this into master @joelostblom ?

2021-02-24 22:36 UTC, joelostblom commented
Yup, thanks for resolving the comments!

2021-02-24 22:36 UTC, merged